// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBajWNeHFyLp6ulZlZb5mVRoqO9pWH964M',
    appId: '1:203950523095:web:79d5737f60d40e8783e692',
    messagingSenderId: '203950523095',
    projectId: 'flutter-coffee-ca7f5',
    authDomain: 'flutter-coffee-ca7f5.firebaseapp.com',
    storageBucket: 'flutter-coffee-ca7f5.appspot.com',
    measurementId: 'G-6HY4GY4BF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNIISTK5oqeg2GXYwDwX5RNG5xiJ3BOY',
    appId: '1:203950523095:android:9d05e1774434691e83e692',
    messagingSenderId: '203950523095',
    projectId: 'flutter-coffee-ca7f5',
    storageBucket: 'flutter-coffee-ca7f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIvv4vDZIobJhcRPAqpSp5YkvEcmJnJcI',
    appId: '1:203950523095:ios:babc4cf9f86af49683e692',
    messagingSenderId: '203950523095',
    projectId: 'flutter-coffee-ca7f5',
    storageBucket: 'flutter-coffee-ca7f5.appspot.com',
    iosClientId: '203950523095-8c9e437fidq5705msreb4aeoinij9odm.apps.googleusercontent.com',
    iosBundleId: 'com.example.page',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIvv4vDZIobJhcRPAqpSp5YkvEcmJnJcI',
    appId: '1:203950523095:ios:babc4cf9f86af49683e692',
    messagingSenderId: '203950523095',
    projectId: 'flutter-coffee-ca7f5',
    storageBucket: 'flutter-coffee-ca7f5.appspot.com',
    iosClientId: '203950523095-8c9e437fidq5705msreb4aeoinij9odm.apps.googleusercontent.com',
    iosBundleId: 'com.example.page',
  );
}
